[project]
name = "100dayofcode"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.123.10",
<<<<<<< HEAD
    "python-dotenv>=1.2.1",
=======
    "uvicorn>=0.38.0",
>>>>>>> d44f93e (test restapi file)
]
